export const NS = {
  ALL: "all",
  HOME: "home",
  COMMON: "common",
  HEADER: "header",
  lottery: "lottery",
  config: "config",
  charge: "charge",
  withdraw: "withdraw",
  ui: "ui",
  msgApi: "msgApi",
  profile: "profile",
  mega: "mega",
  myPurse: "my_purse",
  betHistory: "bet_history",
  sicbo: "sicbo",
  betRefund: "bet_refund",
  vip: "vip",
  keno: "keno",
  sideNavGame: "sideNavGame",
  lotteryResult: "lottery_result",
};
