import SidebarGameNav from "@/components/sidebar-game-nav";

const components = [
  {
    menu_id: 2,
    menu_name: "Miền Bắc",
    list: [
      {
        id: 32,
        name: "Miền Bắc",
        code: "/lottery/xo-so/xsmb",
        series_id: 2,
        week_days: [0, 1, 2, 3, 4, 5, 6],
        isHot: true,
      },
      {
        id: 45,
        name: "M.bắc SVIP 5 phút",
        code: "/lottery/xo-so/300",
        series_id: 2,
        week_days: [0, 1, 2, 3, 4, 5, 6],
        isHot: true,
      },
      // {
      //   id: 63,
      //   name: "Xổ số Miền Bắc",
      //   code: "mb",
      //   series_id: 8,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      //   isNew: true,
      // },
      {
        id: 46,
        name: "M.bắc SVIP 3 phút",
        code: "/lottery/xo-so/180",
        series_id: 2,
        week_days: [0, 1, 2, 3, 4, 5, 6],
        isHot: true,
      },
      {
        id: 49,
        name: "Miền Bắc VIP 2 phút",
        code: "/lottery/xo-so/120",
        series_id: 2,
        week_days: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        id: 48,
        name: "Miền Bắc VIP 75 giây",
        code: "/lottery/xo-so/75",
        series_id: 2,
        week_days: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        id: 47,
        name: "Miền Bắc VIP 45 giây",
        code: "/lottery/xo-so/45",
        series_id: 2,
        week_days: [0, 1, 2, 3, 4, 5, 6],
        isHot: true,
      },
    ],
  },
  {
    menu_id: 9,
    menu_name: "Sicbo",
    list: [
      // {
      //   id: 66,
      //   name: "Sicbo 20 giây",
      //   code: "/lottery/tai-xiu/20",
      //   series_id: 9,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      //   isNew: true,
      // },
      // {
      //   id: 67,
      //   name: "Sicbo 30 giây",
      //   code: "/lottery/tai-xiu/30",
      //   series_id: 9,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      //   isNew: true,
      // },
      // {
      //   id: 68,
      //   name: "Sicbo 40 giây",
      //   code: "/lottery/tai-xiu/40",
      //   series_id: 9,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      //   isNew: true,
      // },
      // {
      //   id: 69,
      //   name: "Sicbo 50 giây",
      //   code: "/lottery/tai-xiu/50",
      //   series_id: 9,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      //   isNew: true,
      // },
      {
        id: 66,
        name: "Sicbo 1 phút",
        code: "/lottery/tai-xiu/60",
        series_id: 9,
        week_days: [0, 1, 2, 3, 4, 5, 6],
        isNew: true,
      },
      {
        id: 67,
        name: "Sicbo 2 phút",
        code: "/lottery/tai-xiu/120",
        series_id: 9,
        week_days: [0, 1, 2, 3, 4, 5, 6],
        isNew: true,
      },
      {
        id: 68,
        name: "Sicbo 3 phút",
        code: "/lottery/tai-xiu/180",
        series_id: 9,
        week_days: [0, 1, 2, 3, 4, 5, 6],
        isNew: true,
      },
      {
        id: 69,
        name: "Sicbo 5 phút",
        code: "/lottery/tai-xiu/300",
        series_id: 9,
        week_days: [0, 1, 2, 3, 4, 5, 6],
        isNew: true,
      },
      // {
      //   id: 71,
      //   name: "Sicbo 1.5 phút",
      //   code: "/lottery/tai-xiu/90",
      //   series_id: 9,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      //   isNew: true,
      // },
    ],
  },
  {
    menu_id: 1,
    menu_name: "Miền Nam",
    isFilter: true,
    list: [
      {
        id: 1,
        name: "Bạc Liêu",
        code: "/lottery/xo-so/xsmn-xsbl",
        series_id: 1,
        week_days: [2],
      },
      {
        id: 2,
        name: "Vũng Tàu",
        code: "/lottery/xo-so/xsmn-xsvt",
        series_id: 1,
        week_days: [2],
      },
      {
        id: 3,
        name: "Tiền Giang",
        code: "/lottery/xo-so/xsmn-xstg",
        series_id: 1,
        week_days: [0],
      },
      {
        id: 4,
        name: "Kiên Giang",
        code: "/lottery/xo-so/xsmn-xskg",
        series_id: 1,
        week_days: [0],
      },
      {
        id: 5,
        name: "Đà Lạt",
        code: "/lottery/xo-so/xsmn-xsld-xsdl",
        series_id: 1,
        week_days: [0],
      },
      {
        id: 6,
        name: "Bình Phước",
        code: "/lottery/xo-so/xsmn-xsbp",
        series_id: 1,
        week_days: [6],
      },
      {
        id: 7,
        name: "Bình Dương",
        code: "/lottery/xo-so/xsmn-xsbd",
        series_id: 1,
        week_days: [5],
      },
      {
        id: 8,
        name: "An Giang",
        code: "/lottery/xo-so/xsmn-xsag",
        series_id: 1,
        week_days: [4],
      },
      {
        id: 9,
        name: "Bình Thuận",
        code: "/lottery/xo-so/xsmn-xsbth",
        series_id: 1,
        week_days: [4],
      },
      {
        id: 10,
        name: "Tây Ninh",
        code: "/lottery/xo-so/xsmn-xstn",
        series_id: 1,
        week_days: [4],
      },
      {
        id: 11,
        name: "Cần Thơ",
        code: "/lottery/xo-so/xsmn-xsct",
        series_id: 1,
        week_days: [3],
      },
      {
        id: 12,
        name: "Hậu Giang",
        code: "/lottery/xo-so/xsmn-xshg",
        series_id: 1,
        week_days: [6],
      },
      {
        id: 15,
        name: "Sóc Trăng",
        code: "/lottery/xo-so/xsmn-xsst",
        series_id: 1,
        week_days: [3],
      },
      {
        id: 17,
        name: "Đồng Nai",
        code: "/lottery/xo-so/xsmn-xsdn",
        series_id: 1,
        week_days: [3],
      },
      {
        id: 42,
        name: "Trà Vinh",
        code: "/lottery/xo-so/xsmn-xstv",
        series_id: 1,
        week_days: [5],
      },
      {
        id: 43,
        name: "Vĩnh Long",
        code: "/lottery/xo-so/xsmn-xsvl",
        series_id: 1,
        week_days: [5],
      },
      // {
      //   id: 57,
      //   name: "Miền Nam VIP 45 giây",
      //   code: "mn45g",
      //   series_id: 1,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      // },
      {
        id: 61,
        name: "Bến Tre",
        code: "ben-tre",
        series_id: 1,
        week_days: [2],
      },
      // {
      //   id: 58,
      //   name: "Miền Nam VIP 1 phút",
      //   code: "mn1p",
      //   series_id: 1,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      //   isNew: true,
      // },
      // {
      //   id: 59,
      //   name: "Miền Nam VIP 90 giây",
      //   code: "mn90g",
      //   series_id: 1,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      //   isNew: true,
      // },
      // {
      //   id: 60,
      //   name: "Miền Nam VIP 2 phút",
      //   code: "mn2p",
      //   series_id: 1,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      //   isNew: true,
      // },
      // {
      //   id: 44,
      //   name: "Miền Nam VIP 5 phút",
      //   code: "mn5p",
      //   series_id: 1,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      // },
      {
        id: 16,
        name: "TP Hồ Chí Minh",
        code: "/lottery/xo-so/xsmn-xshcm-xstp",
        series_id: 1,
        week_days: [1, 6],
      },
      {
        id: 10,
        name: "Cà Mau",
        code: "/lottery/xo-so/xsmn-xscm",
        series_id: 1,
        week_days: [1],
      },
      {
        id: 13,
        name: "Đồng Tháp",
        code: "/lottery/xo-so/xsmn-xsdt",
        series_id: 1,
        week_days: [1],
      },
    ],
  },
  {
    menu_id: 3,
    menu_name: "Miền Trung",
    isFilter: true,
    list: [
      {
        id: 18,
        name: "Đà Nẵng",
        code: "/lottery/xo-so/xsmt-xsdng-xsdna",
        series_id: 3,
        week_days: [3, 6],
      },
      {
        id: 19,
        name: "Thừa Thiên Huế",
        code: "/lottery/xo-so/xsmt-xstth",
        series_id: 3,
        week_days: [0, 1],
      },
      {
        id: 20,
        name: "Quảng Trị",
        code: "/lottery/xo-so/xsmt-xsqt",
        series_id: 3,
        week_days: [4],
      },
      {
        id: 21,
        name: "Phú Yên",
        code: "/lottery/xo-so/xsmt-xspy",
        series_id: 3,
        week_days: [1],
      },
      {
        id: 22,
        name: "Quảng Bình",
        code: "/lottery/xo-so/xsmt-xsqb",
        series_id: 3,
        week_days: [4],
      },
      {
        id: 23,
        name: "Quảng Nam",
        code: "/lottery/xo-so/xsmt-xsqnm-xsqna",
        series_id: 3,
        week_days: [2],
      },
      {
        id: 24,
        name: "Quảng Ngãi",
        code: "/lottery/xo-so/xsmt-xsqng",
        series_id: 3,
        week_days: [6],
      },
      {
        id: 25,
        name: "Ninh Thuận",
        code: "/lottery/xo-so/xsmt-xsnt",
        series_id: 3,
        week_days: [5],
      },
      {
        id: 26,
        name: "Kon Tum",
        code: "/lottery/xo-so/xsmt-xskt",
        series_id: 3,
        week_days: [0],
      },
      {
        id: 27,
        name: "Khánh Hoà",
        code: "/lottery/xo-so/xsmt-xskh",
        series_id: 3,
        week_days: [0, 3],
      },
      {
        id: 28,
        name: "Gia Lai",
        code: "/lottery/xo-so/xsmt-xsgl",
        series_id: 3,
        week_days: [5],
      },
      {
        id: 29,
        name: "Bình Định",
        code: "/lottery/xo-so/xsmt-xsbdi",
        series_id: 3,
        week_days: [4],
      },
      {
        id: 30,
        name: "Đắk Lắk",
        code: "/lottery/xo-so/xsmt-xsdlk",
        series_id: 3,
        week_days: [2],
      },
      {
        id: 31,
        name: "Đắk Nông",
        code: "/lottery/xo-so/xsmt-xsdno",
        series_id: 3,
        week_days: [6],
      },
    ],
  },
  {
    menu_id: 5,
    menu_name: "Mega 6/45",
    list: [
      {
        id: 35,
        name: "Mega 6/45 1 Phút",
        code: "/lottery/mega/1",
        series_id: 5,
        week_days: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        id: 35,
        name: "Mega 6/45 2 Phút",
        code: "/lottery/mega/2",
        series_id: 5,
        week_days: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        id: 35,
        name: "Mega 6/45 3 Phút",
        code: "/lottery/mega/3",
        series_id: 5,
        week_days: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        id: 35,
        name: "Mega 6/45 5 Phút",
        code: "/lottery/mega/5",
        series_id: 5,
        week_days: [0, 1, 2, 3, 4, 5, 6],
      },
    ],
  },
  {
    menu_id: 7,
    menu_name: "Keno",
    list: [
      // {
      //   id: 51,
      //   name: "Keno VIP 20 giây",
      //   code: "/lottery/keno/20",
      //   series_id: 7,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      // },
      // {
      //   id: 52,
      //   name: "Keno VIP 30 giây",
      //   code: "/lottery/keno/30",
      //   series_id: 7,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      // },
      // {
      //   id: 53,
      //   name: "Keno VIP 40 giây",
      //   code: "/lottery/keno/40",
      //   series_id: 7,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      // },
      // {
      //   id: 54,
      //   name: "Keno VIP 50 giây",
      //   code: "/lottery/keno/50",
      //   series_id: 7,
      //   week_days: [0, 1, 2, 3, 4, 5, 6],
      // },
      {
        id: 55,
        name: "Keno VIP 1 phút",
        code: "/lottery/keno/60",
        series_id: 7,
        week_days: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        id: 55,
        name: "Keno VIP 2 phút",
        code: "/lottery/keno/120",
        series_id: 7,
        week_days: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        id: 55,
        name: "Keno VIP 3 phút",
        code: "/lottery/keno/180",
        series_id: 7,
        week_days: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        id: 56,
        name: "Keno VIP 5 phút",
        code: "/lottery/keno/300",
        series_id: 7,
        week_days: [0, 1, 2, 3, 4, 5, 6],
      },
    ],
  },
];

const LotteryLayout: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <div className="hidden space-y-6 p-10 pb-16 md:block container max-w-8xl mx-auto ">
      <div className="flex flex-col space-y-4 lg:flex-row lg:space-x-4 lg:space-y-0 ">
        <aside className="-mx-4 w-[200px] mr-2">
          <SidebarGameNav items={components} />
        </aside>
        {children}
      </div>
    </div>
  );
};

export default LotteryLayout;
